"""add current_balance to Account

Revision ID: 210b0279ad42
Revises: d39f6e11d188
Create Date: 2026-01-09 07:54:21.442146

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '210b0279ad42'
down_revision = 'd39f6e11d188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('current_balance', sa.DECIMAL(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'current_balance')
    # ### end Alembic commands ###