"""add created, updated(at & by)

Revision ID: 3c06d333dc50
Revises: 210b0279ad42
Create Date: 2026-01-09 08:15:34.508128

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3c06d333dc50'
down_revision = '210b0279ad42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'transaction', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'updated_at')
    op.drop_column('transaction', 'created_at')
    op.drop_column('transaction', 'updated_by')
    op.drop_column('transaction', 'created_by')
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'created_at')
    # ### end Alembic commands ###